services:
  # Backend API
  - type: web
    name: symphonaut-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend (Static Site)
  - type: web
    name: symphonaut-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html